/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Thu Nov 21 19:29:04 2019. */

#include "gehub_message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t gschub_PublicKey_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, gschub_PublicKey, E, E, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, gschub_PublicKey, N, E, 0),
    PB_LAST_FIELD
};

const pb_field_t gschub_SharedKey_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, gschub_SharedKey, key, key, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, gschub_SharedKey, cipher, key, &gschub_Cipher_fields),
    PB_LAST_FIELD
};

const pb_field_t gschub_Cipher_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, gschub_Cipher, IV, IV, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, gschub_Cipher, data, IV, 0),
    PB_LAST_FIELD
};

const pb_field_t gschub_CipherTicket_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, gschub_CipherTicket, ID, ID, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, gschub_CipherTicket, cipher, ID, &gschub_Cipher_fields),
    PB_LAST_FIELD
};

const pb_field_t gschub_Client_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, gschub_Client, ID, ID, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, gschub_Client, token, ID, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, gschub_Client, aliasName, token, 0),
    PB_LAST_FIELD
};

const pb_field_t gschub_Ticket_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, gschub_Ticket, address, address, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, gschub_Ticket, secretKey, address, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, gschub_Ticket, clientTicket, secretKey, &gschub_ClientTicket_fields),
    PB_LAST_FIELD
};

const pb_field_t gschub_ClientTicket_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, gschub_ClientTicket, connID, connID, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, gschub_ClientTicket, token, connID, 0),
    PB_LAST_FIELD
};

const pb_field_t gschub_Letter_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, gschub_Letter, type, type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, gschub_Letter, receiver, type, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, gschub_Letter, data, receiver, 0),
    PB_LAST_FIELD
};

const pb_field_t gschub_Reply_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, gschub_Reply, sender, sender, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, gschub_Reply, HMAC, sender, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, gschub_Reply, data, HMAC, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, gschub_Reply, timestamp, data, 0),
    PB_LAST_FIELD
};

const pb_field_t gschub_Data_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, gschub_Data, sender, sender, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, gschub_Data, data, sender, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, gschub_Data, timestamp, data, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(gschub_SharedKey, key) < 65536 && pb_membersize(gschub_SharedKey, cipher) < 65536 && pb_membersize(gschub_Cipher, data) < 65536 && pb_membersize(gschub_CipherTicket, ID) < 65536 && pb_membersize(gschub_CipherTicket, cipher) < 65536 && pb_membersize(gschub_Ticket, clientTicket) < 65536 && pb_membersize(gschub_Letter, data) < 65536 && pb_membersize(gschub_Reply, data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_gschub_PublicKey_gschub_SharedKey_gschub_Cipher_gschub_CipherTicket_gschub_Client_gschub_Ticket_gschub_ClientTicket_gschub_Letter_gschub_Reply_gschub_Data)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for gschub_Cipher.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
